name: Cancel running jobs on PR update
on: pull_request

jobs:
  build:
    name: auto-cancellation-running-action
    runs-on: ubuntu-latest
    steps:
      - uses: fauguste/auto-cancellation-running-action@0.1.2
        with:
          githubToken: ${{ secrets.GH_TOKEN }}
